services:
  optionable:
    container_name: optionable
    image: yomikoye/optionable:latest
    ports:
      - '8096:8080'
    environment:
      - TZ=America/Los_Angeles
      - NODE_ENV=production
      - DATA_DIR=/data
    volumes:
      - /home/smitpatel316/optionable-data:/data
    restart: unless-stopped
